apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service # gonna be a host service URL
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - port: 6379
      targetPort: 6379
