apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3 # 3 pods for multi-server-image - count depends on traffic
  selector:
    matchLabels: # define how deployment find its set of pods
      component: server
  template: # Pod template
    metadata:
      labels:
        component: server # labels of each pod
    spec:
      containers:
        - name: server
          image: stephengrider/multi-server # TODO Add ENV vars
          ports:
            - containerPort: 5000 # expose
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: # use secret
                secretKeyRef: # We wire up a secret to variable
                  name: pgpassword
                  key: PGPASSWORD
