apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment # If there is already existing such an object inside cluster, kuber will try to update this object
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: stephengrider/multi-worker
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
